BEGIN;
-- DDL generated by Postico 1.5.14
-- Not all database features are supported. Do not use for backup.
-- Table Definition ----------------------------------------------
CREATE TABLE projects (
    id SERIAL PRIMARY KEY,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    uuid text NOT NULL DEFAULT gen_random_uuid(),
    name character varying(100) NOT NULL,
    version integer NOT NULL
);

COMMENT ON COLUMN projects.id IS '主キー';
COMMENT ON COLUMN projects.created_at IS '登録日時';
COMMENT ON COLUMN projects.updated_at IS '最終更新日時';
COMMENT ON COLUMN projects.deleted_at IS '最終削除日時';

-- Indices -------------------------------------------------------
CREATE UNIQUE INDEX ix_projects_uuid ON projects(uuid text_ops);
COMMIT;
